<?xml version="1.0" encoding="UTF-8"?>
<annotation>
  <folder>VOC2007</folder>
  <filename>test</filename>
  <source>
    <database></database>
    <annotation></annotation>
    <image></image>
    <flickrid></flickrid>
  </source>
  <owner>
    <flickrid></flickrid>
    <name>zhuoshi</name>
  </owner>
  <size>
    <width>2048</width>
    <height>1600</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>truck</name>
    <pose></pose>
    <type></type>
    <truncated></truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>1135</xmin>
      <ymin>395</ymin>
      <xmax>1748</xmax>
      <ymax>1129</ymax>
    </bndbox>
  </object>
  <object>
    <name>person</name>
    <pose>Unspecified</pose>
    <type></type>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>1179</xmin>
      <ymin>767</ymin>
      <xmax>1660</xmax>
      <ymax>906</ymax>
    </bndbox>
    <attribute>
      <clousecolor>9432416</clousecolor>
      <trousecolor>15563736</trousecolor>
      <hairtype>2008475328</hairtype>
      <clousetype>395212</clousetype>
      <trousetype>514</trousetype>
      <bagtype>0</bagtype>
      <agetype>18809742</agetype>
      <sextype>9433716</sextype>
      <racetype>9432452</racetype>
      <haptype>1