<?xml version="1.0" encoding="UTF-8"?>
<annotation>
  <folder>VOC2007</folder>
  <filename>test</filename>
  <source>
    <database></database>
    <annotation></annotation>
    <image></image>
    <flickrid></flickrid>
  </source>
  <owner>
    <flickrid></flickrid>
    <name>zhuoshi</name>
  </owner>
  <size>
    <width>3392</width>
    <height>2008</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>truck</name>
    <pose></pose>
    <type></type>
    <truncated></truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>2244</xmin>
      <ymin>398</ymin>
      <xmax>3305</xmax>
      <ymax>1653</ymax>
    </bndbox>
  </object>
  <object>
    <name>bigplate</na