<?xml version="1.0" encoding="UTF-8"?>
<annotation>
  <folder>VOC2007</folder>
  <filename>test</filename>
  <source>
    <database></database>
    <annotation></annotation>
    <image></image>
    <flickrid></flickrid>
  </source>
  <owner>
    <flickrid></flickrid>
    <name>zhuoshi</name>
  </owner>
  <size>
    <width>3392</width>
    <height>2008</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>truck</name>
    <pose></pose>
    <type></type>
    <truncated></truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>2290</xmin>
      <ymin>370</ymin>
      <xmax>3359</xmax>
      <ymax>1692</ymax>
    </bndbox>
  </object>
  <object>
    <name>person</name>
    <pose>Unspecified</pose>
    <type></type>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>2470</xmin>
      <ymin>1117</ymin>
      <xmax>3281</xmax>
      <ymax>1333</ymax>
    </bndbox>
    <attribute>
      <clousecolor>9432416</clousecolor>
      <trousecolor>15563736</trousecolor>
      